### ISSUE TITLE
Add auth via apikey

### ISSUE THREAD

**Issue by uggla** [ktrysmt/go-bitbucket#41]
Hello,

Thanks for go-bitbucket library, this is really helpful for us.
As a feature request, could you add authentication via apikey ?

**Comment by ktrysmt** [comment]
Hi, thank you for your comment.

> authentication via apikey

Let me see... Is that said about it?

```
export OAUTH_KEY="key"
export OAUTH_SECRET="secret"
export USER_NAME="yourname"
export REPOSITORY_NAME="yourrepos"
git clone https://x-token-auth:`curl https://bitbucket.org/site/oauth2/access_token -d grant_type=client_credentials -u ${OAUTH_KEY}:${OAUTH_SECRET} \
 | jq -r '.access_token'`@bitbucket.org/$USER_NAME/$REPOSITORY_NAME
```

**Comment by uggla** [comment]
@ktrysmt , nope it seems not working using above line.
 ```
[uggla@ugglalaptop essai-go-bitbucket]$ ./essai-go-bitbucket 
panic: 401 Unauthorized

goroutine 1 [running]:
main.main()
	/home/uggla/workspace/go/src/essai-go-bitbucket/main.go:36 +0x331
```

**Comment by ktrysmt** [comment]
I know that require the header of "Authorization: Bearer YOUR_ACCESS_TOKEN" in HTTP HEADER.
I will add new feature of switch flag in the code.

**Comment by ktrysmt** [comment]
I seem it was fixed.

Would you try the new authorization method;

```
c := bitbucket.NewOAuthbearerToken("INPUT_YOUR_TOKEN")
opt := &bitbucket.RepositoryOptions{
  Owner:    "your_name",
  RepoSlug: "your_repository",
}
res, err := c.Repositories.Repository.Get(opt)
```

**Comment by ktrysmt** [comment]
If you still have problems, please reopen the issue. Thank you.

**Comment by uggla** [comment]
Hello @ktrysmt ,
Unfortunately this is still not working.
```
panic: 401 Unauthorized

goroutine 1 [running]:
main.main()
	/home/uggla/workspace/go/src/essai-go-bitbucket/main.go:40 +0x12f
```

BTW, I cannot reopen this issue. I think this action can only be done by yourself.
So I have just commented this request, but I could open a new one if you wish.

**Comment by ktrysmt** [comment]
@uggla That’s sounds good. Don’t worry about that.

Thanks to you I was able to know about OAuth Bearer Token.

Also please post the issue if there is something.
